### PR TITLE
let us take a more generic view on this

### PR DESCRIPTION
**Pull request by stangls**
I think, this layer has great advantages.
I would like to extend it to be used with any arbitrary data-storage, so I moved central logic to a higher level in the class tree while maintaining the functionality as is.
Based on this I would like to provide a data-store based on JOOQ.

### CODE REVIEW

**Comment by sanity** [comment]
Very cool, need to dig into this to understand it fully.

One advantage of the filesystem that many SQL databases don't have is that they can listen for modifications.  While Shoebox doesn't yet do this with the filesystem (since currently you can't have multiple Stores or Views pointing at the same directory from different JVM instances or even on different servers), the intention is that you will do this.

Also, wondering about the idea of using Jooq.  If using a relational database as a back-end, Shoebox will probably only require a very simple schema which will probably need to be standardized for Shoebox - whereas Jooq seems mainly beneficial for plugging into a pre-existing schema.  It seems that Jooq might not be the ideal database abstraction layer here.  Thoughts?

**Comment by sanity** [comment]
Oh, another question - could we use composition rather than inheritance for this?

So instead of passing a Path into the constructors, we would pass a DirectoryStorageMedium, which would implement a ShoeboxStorageMedium interface that could be replaced by a SQLStorageMedium (need a better name than "StorageMedium"), or a MongoStorageMedium, or perhaps a MemoryStorageMedium (useful for testing)?

**Comment by stangls** [comment]
You are right. In general, listening for modifications on databases is not possible per SQL standard.
But each SQL database has its own way of triggering events of modifications. If not supported, the fallback could be to write events to a special database-table which is scanned periodically - or by using a message broker.

My idea of using Jooq as an underlying storage is the following:
* The programmer uses Jooq to generate a record-class for each table.
* shoebox-jooq allows to automatically map each of those records (i.e tables) to an individual store.
* Then, views can be defined on top of these stores.

**Comment by stangls** [comment]
Using different storage mediums is also a nice approach which is probably easier to handle. The result would be as you described: A simple sql- or no-sql-storage without the need to use libraries like Jooq.

My intention with shoebox-jooq was to allow the programmer to use a well-known storage-system "as-is" and just supply the observation-layer on top of it.

**Comment by sanity** [comment]
That's cool, I can see that being useful for users that are already using Jooq, although for general SQL databases we probably want to use a simpler database abstraction layer that doesn't involve code generation (perhaps Jetbrain's "Exposed"), in any case, that's not a question we need to answer right now.

Yes, the more I think about it the more I think the storage layer should be passed in as a constructor parameter, so:
```kotlin
  val store = Store(DirectoryStore(Paths.get("blah")))
```

However now I'm regretting using the name "Store" for the Store class, maybe rename it to "Shoebox"?

Since View is built on a Store we can also pass a DirectoryStore into its constructor in a similar way.

Watching for changes in the storage medium is also not something we need to worry about too much right now, since we don't currently do this.

Really glad you're helping with this!  Did you find the unit tests useful?  I've tried to make them very thorough.

**Comment by sanity** [comment]
Hey @stangls, would love to get this merged, any thoughts on switching from inheritance to composition, and naming?

**Comment by sanity** [comment]
Ping?

**Comment by stangls** [comment]
Renaming and composition instead of inheritance is a good idea!
But views based on Stores (or Shoeboxes) are still a little bit strange for me, for the following reason:
If we exchange DirectoryStore with SomeSqlStore, the views might not need an additional storage, but let the database handle querying the view's perspective and optimize it.
Unit tests are great. Would not have refactored without them :+1:

**Comment by sanity** [comment]
I agree that Shoebox on top of SQL is somewhat duplicative, the user would probably be better-off just using the SQL database through something like Jooq and forgetting about Shoebox (although they'd lose the observability that way).

I'm thinking more about being about to use a MemoryStore, or perhaps a [ChronicleMap](https://github.com/OpenHFT/Chronicle-Map)Store in place of a DirectoryStore, although there may be use-cases a SqlStore too, despite the duplication.

**Pull request closed without merging**
